import type { Crop } from '@/types';

export const mockCrops: Crop[] = [
  {
    name: 'Lechuga',
    slug: 'lechuga',
    latinName: 'Lactuca sativa',
    shortDescription: 'Crujiente y refrescante, ideal para ensaladas rápidas y frescas.',
    longDescription: 'La lechuga es una hortaliza de hoja verde que se cultiva por sus hojas tiernas y sabrosas. Es un cultivo de ciclo corto, perfecto para huertos urbanos y principiantes por su fácil manejo y rápido crecimiento.',
    imageUrl: 'https://images.unsplash.com/photo-1640958904159-51ae08bd3412?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwzfHxsZXR0dWNlfGVufDB8fHx8MTc1MzE5NDU3M3ww&ixlib=rb-4.1.0&q=80&w=1080',
    aiHint: 'lettuce vegetable',
    difficulty: 'Fácil',
    lifecycle: ['Germinación: 4 a 7 días.', 'Crecimiento vegetativo: 20 a 30 días.', 'Formación de cabeza: 30 a 60 días.', 'Cosecha: después de 60 días.'],
    requirements: {
      watering: 'Riego frecuente pero moderado, mantener el suelo húmedo.',
      climate: 'Clima templado, evitar calor extremo (15-20°C).',
      space: '20-30 cm entre plantas.',
      pests: 'Pulgones, babosas y caracoles.',
      fertilizers: 'Compost o abono rico en nitrógeno al inicio del cultivo.',
    },
    sowingGuide: {
      pot: 'Macetas de al menos 20cm de profundidad. Usar sustrato ligero.',
      soil: 'Siembra directa en surcos poco profundos, o en semilleros para trasplante.',
      hydroponics: 'Excelente para sistemas NFT y de raíz flotante.',
    },
  },
  {
    name: 'Tomate',
    slug: 'tomate',
    latinName: 'Solanum lycopersicum',
    shortDescription: 'Fruto jugoso y versátil, esencial en la cocina colombiana.',
    longDescription: 'El tomate es una de las hortalizas más populares y cultivadas en el mundo. Requiere más cuidados que la lechuga, como tutores para sostener su crecimiento y podas regulares, pero la recompensa es una cosecha abundante y sabrosa.',
    imageUrl: 'https://images.unsplash.com/photo-1607305387299-a3d9611cd469?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHx0b21hdG98ZW58MHx8fHwxNzUzMTk0NDg4fDA&ixlib=rb-4.1.0&q=80&w=1080',
    aiHint: 'tomato plant',
    difficulty: 'Media',
    lifecycle: ['Germinación: 5 a 10 días.', 'Crecimiento vegetativo: 30 a 40 días.', 'Floración: a los 45-60 días.', 'Fructificación: desde los 70 días en adelante.'],
     requirements: {
      watering: 'Riego regular y profundo, especialmente durante la floración y fructificación. Evitar mojar las hojas.',
      climate: 'Clima cálido y soleado, necesita al menos 6 horas de sol directo (21-29°C).',
      space: '40-60 cm entre plantas, necesita tutores o jaulas.',
      pests: 'Mosca blanca, araña roja, mildiu.',
      fertilizers: 'Abono equilibrado rico en potasio y fósforo durante la floración.',
    },
    sowingGuide: {
      pot: 'Macetas grandes, de mínimo 40cm de profundidad. Buen drenaje es crucial.',
      soil: 'Trasplantar las plántulas cuando tengan 4-6 hojas verdaderas.',
      hydroponics: 'Apto para sistemas de goteo con sustratos como fibra de coco o perlita.',
    },
  },
  {
    name: 'Maíz',
    slug: 'maiz',
    latinName: 'Zea mays',
    shortDescription: 'Un pilar de la alimentación colombiana, desde arepas hasta mazamorra.',
    longDescription: 'El maíz es un cultivo fundamental en la cultura y dieta de Colombia. Su cultivo a gran escala es complejo, pero es posible tener una pequeña plantación en un huerto grande, prestando atención a la polinización para obtener buenas mazorcas.',
    imageUrl: 'https://images.unsplash.com/photo-1634467524884-897d0af5e104?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw1fHxtYSVDMyVBRHp8ZW58MHx8fHwxNzUzMTk0NjM1fDA&ixlib=rb-4.1.0&q=80&w=1080',
    aiHint: 'corn field',
    difficulty: 'Difícil',
    lifecycle: ['Siembra', 'Germinación (7-10 días)', 'Crecimiento rápido (30-60 días)', 'Polinización y formación de mazorca (60-80 días)', 'Cosecha (90-120 días)'],
    requirements: {
      watering: 'Requiere mucha agua, especialmente durante la polinización y llenado de grano.',
      climate: 'Clima cálido y mucho sol. Sensible a las heladas.',
      space: 'Plantar en bloques (ej. 4x4) en lugar de una sola fila para asegurar la polinización por viento. 30-40 cm entre plantas.',
      pests: 'Gusano cogollero, pájaros.',
      fertilizers: 'Muy exigente en nitrógeno. Requiere abonado fuerte.',
    },
    sowingGuide: {
      pot: 'No recomendado para macetas debido a su tamaño y necesidad de polinización cruzada.',
      soil: 'Siembra directa en el suelo cuando la temperatura sea consistentemente cálida.',
      hydroponics: 'No es una opción común o práctica para el cultivo de maíz.',
    },
  },
  {
    name: 'Papa',
    slug: 'papa',
    latinName: 'Solanum tuberosum',
    shortDescription: 'Tubérculo versátil y fundamental en la gastronomía andina.',
    longDescription: 'La papa es un cultivo esencial en las zonas frías de Colombia. Se cultiva por sus tubérculos ricos en almidón. Requiere suelos bien drenados y es sensible a la humedad excesiva, que puede causar enfermedades.',
    imageUrl: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxwb3RhdG98ZW58MHx8fHwxNzU2OTk5MzIyfDA&ixlib=rb-4.1.0&q=80&w=1080',
    aiHint: 'potato plant',
    difficulty: 'Media',
    lifecycle: ['Siembra de tubérculos', 'Brotación (15-25 días)', 'Crecimiento vegetativo (30-50 días)', 'Tuberización (50-90 días)', 'Cosecha (100-140 días)'],
    requirements: {
      watering: 'Riego moderado. Mantener humedad sin encharcar. Suspender riego antes de la cosecha.',
      climate: 'Clima frío a templado (10-20°C). Sensible a heladas tardías.',
      space: '30-40 cm entre plantas, en surcos de 70-90 cm de separación.',
      pests: 'Gota (Phytophthora infestans), pulguilla.',
      fertilizers: 'Rico en fósforo y potasio para el desarrollo de tubérculos.',
    },
    sowingGuide: {
      pot: 'Posible en macetas o sacos muy grandes (más de 50L), aporcando tierra a medida que crece.',
      soil: 'Sembrar trozos de papa con "ojos" (brotes) en surcos y cubrir con tierra.',
      hydroponics: 'Poco común, pero posible en sistemas de aeroponía.',
    },
  },
  {
    name: 'Café',
    slug: 'cafe',
    latinName: 'Coffea arabica',
    shortDescription: 'El grano insignia de Colombia, famoso por su aroma y sabor suave.',
    longDescription: 'El café es un arbusto perenne que produce las famosas cerezas de café. Es un cultivo de largo plazo que requiere condiciones específicas de altitud y clima. Es el corazón de la economía en muchas regiones montañosas del país.',
    imageUrl: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw1fHxjb2ZmZWV8ZW58MHx8fHwxNzU2OTgxNDc1fDA&ixlib=rb-4.1.0&q=80&w=1080',
    aiHint: 'coffee branch',
    difficulty: 'Difícil',
    lifecycle: ['Siembra (almácigo)', 'Trasplante (6-12 meses)', 'Crecimiento (2-3 años)', 'Primera floración y cosecha (a partir del 3er año)', 'Producción continua'],
    requirements: {
      watering: 'Riego constante, especialmente en épocas secas. Buen drenaje es vital.',
      climate: 'Zonas montañosas subtropicales (1.200-1.800 msnm), con temperaturas de 18-24°C y sombra parcial.',
      space: '2-3 metros entre plantas.',
      pests: 'Broca del café, roya.',
      fertilizers: 'Abonos ricos en nitrógeno, fósforo y potasio, aplicados en ciclos.',
    },
    sowingGuide: {
      pot: 'Se puede mantener como planta ornamental en macetas grandes, pero la producción será limitada.',
      soil: 'Se siembra en almácigos y luego se trasplantan las plántulas al campo definitivo.',
      hydroponics: 'No es viable para producción comercial.',
    },
  },
  {
    name: 'Banano',
    slug: 'banano',
    latinName: 'Musa paradisiaca',
    shortDescription: 'Fruta tropical energética y rica en potasio, cultivada en zonas cálidas.',
    longDescription: 'La planta de banano es una hierba gigante que produce racimos de fruta. Es un cultivo de rápido crecimiento en climas tropicales que requiere grandes cantidades de agua y nutrientes para ser productivo.',
    imageUrl: 'https://images.unsplash.com/photo-1603833665858-e61d17a86224?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw1fHxiYW5hbmF8ZW58MHx8fHwxNzU2OTk5NDEzfDA&ixlib=rb-4.1.0&q=80&w=1080',
    aiHint: 'banana plant',
    difficulty: 'Media',
    lifecycle: ['Siembra de cormos o hijuelos', 'Crecimiento vegetativo (9-12 meses)', 'Floración y formación del racimo', 'Cosecha del racimo (3-4 meses después de floración)'],
    requirements: {
      watering: 'Abundante y regular. Es una planta que consume mucha agua.',
      climate: 'Clima cálido y húmedo (26-30°C). No tolera el frío.',
      space: 'Mínimo 3x3 metros por planta.',
      pests: 'Sigatoka negra, picudo negro.',
      fertilizers: 'Muy exigente en potasio y nitrógeno. Requiere fertilización constante.',
    },
    sowingGuide: {
      pot: 'No práctico para producción de fruta, solo como ornamental muy grande.',
      soil: 'Se siembran los cormos o hijuelos directamente en el suelo bien preparado.',
      hydroponics: 'Inviable a escala productiva.',
    },
  },
];
